/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.gt.gui.window;

import de.gt.api.gps.GPSKey;
import de.gt.api.relay.Receiver;
import gov.nasa.worldwind.BasicModel;
import gov.nasa.worldwind.avlist.AVKey;
import gov.nasa.worldwind.awt.WorldWindowGLCanvas;
import gov.nasa.worldwind.geom.Position;
import gov.nasa.worldwind.layers.RenderableLayer;
import gov.nasa.worldwind.render.AnnotationAttributes;
import gov.nasa.worldwind.render.GlobeAnnotation;
import gov.nasa.worldwind.render.Polyline;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//de.gt.gui.window//LivePathEarth//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "LivePathEarthTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "output", openAtStartup = false)
@ActionID(category = "Window", id = "de.gt.gui.window.LivePathEarthTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_LivePathEarthAction",
        preferredID = "LivePathEarthTopComponent"
)
@Messages({
    "CTL_LivePathEarthAction=LivePathEarth",
    "CTL_LivePathEarthTopComponent=LivePathEarth Window",
    "HINT_LivePathEarthTopComponent=This is a LivePathEarth window"
})
public final class EarthTopComponent extends TopComponent implements Receiver {
    
    private static final AnnotationAttributes ATTRIBS = new AnnotationAttributes();
    static {
        ATTRIBS.setAdjustWidthToText(AVKey.SIZE_FIT_TEXT);
    }
    
    private final List<Position> positions = new ArrayList<>();
    
    private final GPSKey k;
    
    private final WorldWindowGLCanvas wwd;
    private final RenderableLayer layer;
    private final Polyline path;
    
    public EarthTopComponent(GPSKey k) {
        this.k = k;
        
        initComponents();
        setName(Bundle.CTL_LivePathEarthTopComponent());
        setToolTipText(Bundle.HINT_LivePathEarthTopComponent());
        wwd = new WorldWindowGLCanvas();
        BasicModel bm = new BasicModel();
        wwd.setModel(bm);
        layer = new RenderableLayer();
        path = new Polyline();
        layer.addRenderable(path);
        bm.getLayers().add(layer);
    }

    private void add(Position p, GlobeAnnotation a) {
        positions.add(p);
        path.setPositions(positions);
        layer.addRenderable(a);
        wwd.redraw();
    }
    
    @Override
    public void receive(Map<String, Double> datum) {
        double latitude = datum.get(k.getLatitudeKey());
        double longitude = datum.get(k.getLongitudeKey());
        double altitude = datum.get(k.getAltitudeKey());
        Position p = Position.fromDegrees(latitude, longitude, altitude);
        StringBuilder b = new StringBuilder();
        datum.entrySet().stream()
                .map(e -> String.format("%s: %s\n", e.getKey(), e.getValue()))
                .forEach(b::append);
        GlobeAnnotation a = new GlobeAnnotation(b.toString(), p, ATTRIBS);
        add(p, a);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
